---
spring:
  jpa:
  #    show-sql: false
  mvc.favicon.enabled: false

jwt:
  clientId: chatbot-admin
  client-secret: secret
  accessTokenValidititySeconds: 1800
  refreshTokenValiditySeconds: 1800
